services:
  vault:
    image: hashicorp/vault:latest
    container_name: security_vault
    command: server
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/config:/vault/config
      - vault_data:/vault/file

  vault-init:
    image: hashicorp/vault:latest
    container_name: security_vault_init
    depends_on:
      - vault
    environment:
      - VAULT_ADDR=http://vault:8200
    volumes:
      - ./vault/config:/vault/config
      - vault_data:/vault/file
    entrypoint: /bin/sh
    command: -c "sh /vault/config/init-vault.sh"

  middleware:
    build:
      context: .
      dockerfile: cmd/middleware/Dockerfile
    container_name: security_middleware
    ports:
      - "8000:8000"
    environment:
      - MIDDLEWARE_LISTEN_PORT=8000
      - MIDDLEWARE_DB_HOST=host.docker.internal 
      - MIDDLEWARE_DB_PORT=5432
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
      - MIDDLEWARE_ENCRYPTION_MODE=shared
    depends_on:
      - vault
      - vault-init
    volumes:
      - ./certs:/certs

volumes:
  vault_data: